package nl.svb.bre.domain.enums;

public enum Definitiecode {

    // Examples
    EXAMPLE_JOURNEY,
    EXAMPLE_VEHICLE,
    EXAMPLE_JOURNEY_BICYCLE,
    EXAMPLE_CHARGING_TIME_BICYCLE,
    EXAMPLE_CHARGING_TIME,
    EXAMPLE_DURATION,
    EXAMPLE_ELECTRIC,
    EXAMPLE_AVERAGE_SPEED,
    EXAMPLE_DISTANCE,
    EXAMPLE_ELECTRIC_DISTANCE_BICYCLE,

    D1_DUUR_HOOGTE_MAATREGEL,
    D11_EISEN_MAATREGEL_SANCTIE,
    D111_MEDEWERKINGSVERPLICHTING_OVERTREDEN,
    D1112_UITZONDERING_MEDEWERKINGSVERPLICHTING_AKW,
    D11121_UITZONDERING_MEDEWERKINGSVERPLICHTING_VERHUIZING_BUITENLAND_AKW,

}
