package nl.svb.bre.domain.enums;

public enum Definitiecode {

    // Examples
    EXAMPLE_JOURNEY,
    EXAMPLE_VEHICLE,
    EXAMPLE_JOURNEY_BICYCLE,
    EXAMPLE_CHARGING_TIME_BICYCLE,
    EXAMPLE_CHARGING_TIME,
    EXAMPLE_DURATION,
    EXAMPLE_ELECTRIC,
    EXAMPLE_AVERAGE_SPEED,
    EXAMPLE_DISTANCE,
    EXAMPLE_ELECTRIC_DISTANCE_BICYCLE,

    D1_DUUR_HOOGTE_MAATREGEL,
    D11_EISEN_MAATREGEL_SANCTIE,
    D12_BASISBEDRAG_IS_LAGER_DAN_MINIMUM_BEDRAG,
    D111_MEDEWERKINGSVERPLICHTING_OVERTREDEN,
    D112_UITKERING_WAARDE_OP_MAATREGEL_SANCTIE,
    D113_SVB_ZIET_AF_VAN_HET_OPLEGGEN_VAN_EEN_MAATREGEL,
    D121_BASISBEDRAG_MAATREGEL,
    D122_MINIMUMBEDRAG_MAATREGEL,
    D1111_OVERTREDEN_SOORT_VERPLICHTING_AKW,
    D1112_UITZONDERING_MEDEWERKINGSVERPLICHTING_AKW,
    D1131_PERSOON_VERWIJTBAAR,
    D1211_MATE_VAN_VERWIJTBAARHEID,
    D1212_AANMERKING_UITKERINGSBEDRAG,
    D1213_TYPE_MAATREGELSANCTIE,
    D11121_UITZONDERING_MEDEWERKINGSVERPLICHTING_VERHUIZING_BUITENLAND_AKW,
    D11311_DOOR_EEN_BUITENGEWONE_OMSTANDIGHEID_WAS_HET_NAKOMEN_VAN_DE_VERPLICHTING_FEITELIJK_ONMOGELIJK,
    D11312_BETROKKENE_KAN_ER_IN_REGELIJKHEID_VAN_UITGAAN_DAT_DE_SVB_AL_OP_DE_HOOGTE_IS,
    D12111_DOOR_DE_EMOTIONELE_ONTWRICHTING_IS_DE_OVERTREDING_VERMINDERD_TOE_TE_REKENEN,
    D12112_DOOR_DE_GEESTELIJKE_TOESTAND_IS_DE_OVERTREDING_VERMINDERD_TOE_TE_REKENEN,
    D12113_VERMINDERD_TOE_TE_REKENEN,
    D12121_BEDRAG_AKW,
    D12131_RECIDIVE,
    D113111_BUITENGEWONE_OMSTANDIGHEID,
    SVB_LEEFTIJD_KIND1,
    SVB_LEEFTIJD_KIND2,

    D2_PERSOON_HEEFT_RECHT_OP_TOESLAG,
    D21_PERSOON_VOLDOET_AAN_DE_LEEFTIJDSEIS,
    D22_PERSOON_VOLDOET_AAN_DE_INKOMENSEIS,
    D23_PERSOON_IS_MINIMAAL_50_DAGEN_ACHTEREENVOLGENS_VERZEKERD_GEWEEST,
    D3_VERZEKERD_IN_PERIODE
}
