package nl.svb.bre.domain.enums;

public enum Definitiecode {

    // Examples
    EXAMPLE_JOURNEY,
    EXAMPLE_VEHICLE,
    EXAMPLE_JOURNEY_BICYCLE,
    EXAMPLE_CHARGING_TIME_BICYCLE,
    EXAMPLE_CHARGING_TIME,
    EXAMPLE_DURATION,
    EXAMPLE_ELECTRIC,
    EXAMPLE_AVERAGE_SPEED,
    EXAMPLE_DISTANCE,
    EXAMPLE_ELECTRIC_DISTANCE_BICYCLE

}
